# render.yaml - Versión final (solo para la API)

services:
  # El único servicio que definimos aquí es nuestra API
  - type: web
    name: ecommerce-api
    plan: free
    rootDir: back/ecommerce-flarano-herrera
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    # Importante: Las variables de entorno las configuraremos manualmente
    # para conectar con la base de datos que ya creamos.