version: '3.9'

services:
  backend:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: dbsoyhenry
      DB_NAME: ecommerce
      CLOUDINARY_NAME: dxifqh6xt
      CLOUDINARY_API_KEY: 629533663712939
      CLOUDINARY_API_SECRET: KA4UVtSo_s44AKeye1NG8LsYxek
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbsoyhenry
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
