version: '3.9'

services:
  backend:
    container_name: nest-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
       condition: service_healthy
    command: npm run start:dev

  postgres:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: # <-- 2. MODIFICACIÓN: Añade esta sección completa.
       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
       interval: 10s
       timeout: 5s
       retries: 5

volumes:
  pgdata:
