services:
  - type: web
    name: ecommerce-backend
    env: docker
    dockerfilePath: back/ecommerce-flarano-herrera/Dockerfile
    branch: main
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: postgresql://pim4_postgresql_ecommerce_user:qHIISpniv9KHim8cxSyN3ghw6DgW9n4N@dpg-d2d3kt3uibrs73fq4qng-a.virginia-postgres.render.com/pim4_postgresql_ecommerce?sslmode=require
      - key: CLOUDINARY_NAME
        fromSecret: CLOUDINARY_NAME
      - key: CLOUDINARY_API_KEY
        fromSecret: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        fromSecret: CLOUDINARY_API_SECRET
