# render.yaml - Versión completa y corregida

services:
  # 1. Servicio de Base de Datos PostgreSQL
  - type: psql # El tipo de servicio para una base de datos PostgreSQL
    name: ecommerce-db # Nombre para tu servicio de base de datos
    plan: free # El plan de servicio (el gratuito es ideal para empezar)
    databaseName: ecommerce # El nombre de la base de datos que se creará
    postgresMajorVersion: 16 # La versión de PostgreSQL

  # 2. Servicio Web para la API de NestJS
  - type: web
    name: ecommerce-api # Nombre para tu servicio de API
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile # Ruta a tu Dockerfile
    healthCheckPath: / # Ruta para que Render verifique si tu app está funcionando
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db # Debe coincidir con el nombre del servicio 'psql'
          property: connectionString
      - key: PORT
        value: 10000
      # Recuerda añadir tus secretos (CLOUDINARY, JWT_SECRET)
      # directamente en el Dashboard de Render, no aquí.
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false